minimum_pre_commit_version: 4.5.0
default_install_hook_types:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-illegal-windows-names

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.1
    hooks:
      - id: clang-format
        types_or:
          - c
          - c++
        files: ^src/.*\.(h|hpp|c|cc|cpp)$
